import { useState, useEffect } from "react";
import { AlertCircle, Loader2, Sparkles, RefreshCw } from "lucide-react";
import { Button } from "./ui/button";
import { useAppContext } from "../context/AppContext";
import { generateWorkoutPlan } from "../services/geminiService";

// ---- Fallback static workout ----

const fallbackWorkoutPlan = {
  exercises: [
    { name: "Push-ups", sets: 3, reps: "15-20", category: "Strength", notes: "Keep core tight" },
    { name: "Pull-ups", sets: 3, reps: "8-12", category: "Strength", notes: "Full range of motion" },
    { name: "Dips", sets: 3, reps: "12-15", category: "Strength", notes: "Lean slightly forward" },
    { name: "Squats", sets: 4, reps: "20", category: "Strength", notes: "Go below parallel" },
    { name: "Lunges", sets: 3, reps: "15 each leg", category: "Strength", notes: "Step wide" },
    { name: "Plank", sets: 3, reps: "60 seconds", category: "Core", notes: "Keep body straight" },
    { name: "Burpees", sets: 3, reps: "12", category: "Cardio", notes: "Full explosive movement" },
  ],
  cardio: [
    "Running: 30 minutes, 3-4 times per week",
    "Cycling: 45 minutes, 2-3 times per week",
    "Swimming: 30 minutes, 2 times per week",
    "HIIT: 20 minutes, 2-3 times per week",
  ],
  recovery: [
    "Get 7-9 hours of quality sleep each night",
    "Stay hydrated (3-4 liters of water daily)",
    "Stretch for 10-15 minutes post-workout",
    "Take rest days to allow muscle recovery",
    "Consider foam rolling for muscle tension",
  ],
  notes: "This is a general fitness plan. Complete your profile in the Home tab for a personalized AI-generated workout!",
};

export default function WorkoutTab() {
  const { userProfile, reportData, workoutPlan, setWorkoutPlan, isGeneratingWorkout, setIsGeneratingWorkout } = useAppContext();
  const [aiGenerated, setAiGenerated] = useState(false);
  const [error, setError] = useState("");

  // Load fallback if no plan exists
  useEffect(() => {
    if (!workoutPlan) {
      setWorkoutPlan(fallbackWorkoutPlan);
    }
  }, [workoutPlan, setWorkoutPlan]);

  const handleGenerateWithAI = async () => {
    setIsGeneratingWorkout(true);
    setError("");
    setAiGenerated(false);
    try {
      const plan = await generateWorkoutPlan(userProfile, reportData);
      setWorkoutPlan(plan);
      setAiGenerated(true);
    } catch (err: any) {
      console.error("Workout generation error:", err);
      if (err.message?.includes("Gemini API") || err.message?.includes("Failed to parse")) {
        setError("AI generation failed. Using default plan. Please check your Gemini API key.");
      } else {
        setError("Failed to generate workout plan. Try again.");
      }
      if (!workoutPlan) {
        setWorkoutPlan(fallbackWorkoutPlan);
      }
    } finally {
      setIsGeneratingWorkout(false);
    }
  };

  const currentPlan = workoutPlan || fallbackWorkoutPlan;

  const categoryColors: Record<string, string> = {
    Strength: "text-[#ccff00]",
    Cardio: "text-red-400",
    Core: "text-purple-400",
    Flexibility: "text-blue-400",
  };

  return (
    <div className="space-y-8">
      <div className="flex justify-between items-center">
        <h1 className="text-4xl font-bold text-white">Training Matrix</h1>
        <Button
          onClick={handleGenerateWithAI}
          disabled={isGeneratingWorkout}
          className="bg-[#ccff00] text-black hover:bg-[#b8e600] rounded-xl px-4 py-2 font-semibold"
        >
          {isGeneratingWorkout ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <RefreshCw className="mr-2 h-4 w-4" />
              AI Generate
            </>
          )}
        </Button>
      </div>

      {/* Personalization Info */}
      {userProfile?.goal && (
        <div className="bg-gradient-to-r from-[#ccff00]/10 to-transparent border border-[#ccff00]/30 rounded-2xl p-4">
          <p className="text-sm text-gray-300">
            ✨ <span className="text-[#ccff00] font-semibold">Tailored for</span> — {userProfile.goal === "lose" ? "Weight Loss" : userProfile.goal === "gain" ? "Muscle Gain" : "Maintenance"}
            {reportData && <span className="text-purple-400"> • Adjusted for medical report insights</span>}
          </p>
        </div>
      )}

      {/* AI Generated Badge */}
      {aiGenerated && (
        <div className="bg-purple-500/10 border border-purple-500/30 rounded-2xl p-4 flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-purple-400" />
          <p className="text-sm text-purple-300">
            This workout plan was generated by AI based on your profile{reportData ? " and medical report" : ""}.
          </p>
        </div>
      )}

      {/* Error */}
      {error && (
        <div className="bg-red-500/10 border border-red-500/30 rounded-2xl p-4">
          <p className="text-sm text-red-400">{error}</p>
        </div>
      )}

      {/* AI Notes */}
      {currentPlan.notes && (
        <div className="bg-[#18181b] rounded-3xl p-6 border border-gray-800">
          <p className="text-gray-300 text-sm">{currentPlan.notes}</p>
        </div>
      )}

      {/* Workout Plan */}
      <div className="bg-[#18181b] rounded-3xl p-8 border border-gray-800">
        <h3 className="text-2xl font-bold text-white mb-6">Exercise Plan</h3>
        <div className="space-y-4">
          {currentPlan.exercises.map((exercise, index) => (
            <div key={index} className="flex items-start gap-4 p-4 bg-[#27272a] rounded-xl border border-gray-700">
              <div className="w-8 h-8 bg-[#ccff00] rounded-full flex items-center justify-center flex-shrink-0">
                <span className="text-black font-bold">{index + 1}</span>
              </div>
              <div className="flex-1">
                <div className="flex justify-between items-start">
                  <span className="text-gray-200 text-lg font-medium">{exercise.name}</span>
                  <span className={`text-xs font-medium px-2 py-1 rounded-lg bg-gray-800 ${categoryColors[exercise.category] || "text-gray-400"}`}>
                    {exercise.category}
                  </span>
                </div>
                <p className="text-gray-400 text-sm mt-1">
                  {exercise.sets} sets × {exercise.reps}
                  {exercise.notes && <span className="text-gray-500"> — {exercise.notes}</span>}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Cardio Recommendations */}
      <div className="bg-gradient-to-br from-purple-500/10 to-[#ccff00]/10 rounded-3xl p-8 border border-purple-500/30">
        <h3 className="text-2xl font-bold text-white mb-4">Cardio Recommendations</h3>
        <div className="space-y-3 text-gray-300">
          {currentPlan.cardio.map((item, index) => (
            <p key={index}>• <span className="text-[#ccff00] font-medium">{item.split(":")[0]}:</span>{item.includes(":") ? item.substring(item.indexOf(":") + 1) : item}</p>
          ))}
        </div>
      </div>

      {/* Recovery Section */}
      <div className="bg-[#18181b] rounded-3xl p-8 border border-gray-800">
        <h3 className="text-2xl font-bold text-white mb-4">Recovery Tips</h3>
        <div className="space-y-3 text-gray-300">
          {currentPlan.recovery.map((tip, index) => (
            <p key={index}>✓ {tip}</p>
          ))}
        </div>
      </div>

      {/* Warning */}
      <div className="bg-red-500/10 border border-red-500/30 rounded-2xl p-6">
        <div className="flex items-start gap-3">
          <AlertCircle className="w-6 h-6 text-red-400 flex-shrink-0 mt-0.5" />
          <div>
            <h4 className="text-red-400 font-semibold mb-2">Important Safety Notice</h4>
            <p className="text-gray-400 text-sm">
              Always warm up before exercising and cool down afterward. If you experience pain, dizziness, or discomfort, stop immediately and consult a healthcare professional. Gradually increase intensity to avoid injury.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
